version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: splitwise
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: ./server
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/splitwise
    depends_on:
      - postgres
    volumes:
      - ./server:/app

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

volumes:
  postgres_data: 